# Generated by Django 4.0.4 on 2022-05-27 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, unique=True)),
                ('language', models.CharField(blank=True, choices=[('Español', 'Es'), ('English', 'En')], max_length=50, null=True)),
                ('phrase', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easiness', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('last_review', models.DateField(blank=True, null=True)),
                ('interval', models.IntegerField(default=0)),
                ('repetitions', models.IntegerField(default=0)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='wordbook.wordterm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_book', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
