# Generated by Django 4.0.4 on 2022-05-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordterm',
            name='word',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
