# Generated by Django 4.0.4 on 2022-05-23 00:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordbook', '0002_alter_wordterm_word'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBook',
            new_name='FlashCard',
        ),
    ]
