# Generated by Django 4.0.4 on 2022-04-26 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbook', '0004_userbook_next_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='easiness',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='interval',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
